#! /bin/sh

sxhkd &
nitrogen --restore &
picom --config /home/irmo/.config/picom/picom.conf &
urxvtd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Set the border colors for your windows for focused, active and inactive ones.
bspc config normal_border_color "#F808E9"
bspc config active_border_color "#13CA91"
bspc config focused_border_color "#13CA91"

#Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "#F808E9"

#place the focus on where the mouse is; if you like clicking windows to focus, comment this line
bspc config focus_follows_pointer true

# Polybars
/home/irmo/.config/polybar/launch.sh &
