(deftheme spaceman-jellyfish
  "Colors to match the spaceman-jellyfish colorscheme I'm using in bspwm.")

(custom-theme-set-faces
 'spaceman-jellyfish
 '(default ((t (:inherit nil :stipple nil :background "#0F161E" :foreground "#17BA6C" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 105 :width normal :foundry "Bits" :family "Bitstream Vera Sans Mono"))))
 '(cursor ((t (:background "#86E3C2"))))
 '(fixed-pitch ((t (:family "Bitstream Vera Sans Mono" :foundry "Bits" :width normal :height 105 :weight normal :slant normal))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#F808E9"))))
 '(homoglyph ((t (:foreground "#F808E9"))))
 '(minibuffer-prompt ((t (:foreground "#86E3C2"))))
 '(highlight ((t (:background "#86E3C2" :foreground "#0F161E"))))
 '(region ((t (:background "#32353f"))))
 '(shadow ((t (:foreground "#62686E"))))
 '(secondary-selection ((t (:background "#595A58"))))
 '(trailing-whitespace ((t (:background "#BC4F4F"))))
 '(font-lock-builtin-face ((t (:foreground "#86D3B2"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#595A58"))))
 '(font-lock-constant-face ((t (:foreground "#578F8F"))))
 '(font-lock-doc-face ((t (:foreground "#5d5d4f" :inherit (font-lock-comment-face)))))
 '(font-lock-function-name-face ((t (:foreground "#faf4c6"))))
 '(font-lock-keyword-face ((t (:foreground "#86D3B2"))))
 '(font-lock-negation-char-face ((t (:inherit bold :foreground "#28AC56"))))
 '(font-lock-preprocessor-face ((t (:inherit bold :foreground "#28AC56"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit bold :foreground "#28AC56"))))
 '(font-lock-regexp-grouping-construct ((t (:inherit bold :foreground "#28AC56"))))
 '(font-lock-string-face ((t (:foreground "#B8A73A"))))
 '(font-lock-type-face ((t (:foreground "#8181a6"))))
 '(font-lock-variable-name-face ((t (:foreground "#A125A5"))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:foreground "#86E3C2" :underline t :weight bold))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#272727"))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#c2c2b0" :background "#171717"))))
 '(mode-line ((t (:box nil :foreground "#bbc2cf" :background "#32353f"))))
 '(mode-line-buffer-id ((t (:foreground "#28AC56" :weight bold))))
 '(mode-line-emphasis ((t (:foreground "#86E3C2"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#6a6d62" :background "#171717"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:background "#BC4F4F" :foreground "#0F161E" :weight bold))))
 '(lazy-highlight ((t (:background "#86D3B2" :foreground "#555555" :weight bold))))
 '(match ((t (:background "#1d2127" :foreground "#B8A73A" :weight bold))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'spaceman-jellyfish)
